from django.contrib import admin
from dashboard.models import *
# Register your models here.

# admin.site.register(DataCenterCountry)
admin.site.register(DataCenterState)
admin.site.register(UserProfile)
# admin.site.register(DeviceEquipement)
# admin.site.register(DC)
# admin.site.register(RR)
admin.site.register(WebsiteLinks)
admin.site.register(Product)
admin.site.register(Notif)
admin.site.register(addDataCenter)
admin.site.register(AddDevice)
admin.site.register(DeviceDetails)
admin.site.register(addDataCenterRow)
admin.site.register(AddDataCenterRackcabinet)
admin.site.register(PatchPanel)
admin.site.register(PatchPanelPort)
admin.site.register(Topology)
# admin.site.register(Uptime)
# admin.site.register(ProcessUtil)
# admin.site.register(Browser)
# admin.site.register(Series)
admin.site.register(DeviceTemplate)
# admin.site.register(ServerData)
admin.site.register(DeviceCapibility)
admin.site.register(CameraMonitor)
admin.site.register(ContactUs)
admin.site.register(RaiseTicket)
# admin.site.register(AnsibleOutput)
admin.site.register(SSHServers)
admin.site.register(Cabels)
admin.site.register(TempIPDevice)
admin.site.register(PduPortForm)
admin.site.register(ApplianceDataCollection)
admin.site.register(DashboardDataCollection)
admin.site.register(License)
admin.site.register(TestModal)
admin.site.register(SNMPDataCollection)
admin.site.register(SNMPInterfaceDataCollection)
admin.site.register(DeviceSetting)
admin.site.register(SnmpDeviceSetting)
admin.site.register(TerminalLog)
admin.site.register(StartApp)
admin.site.register(MyDevice)
admin.site.register(MyDeviceSNMPData)
admin.site.register(MyDeviceSNMPInterface)

from .models import SSHServers