# Generated by Django 3.2.5 on 2022-07-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_storage_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage_Summary',
        ),
    ]
