# Generated by Django 3.2.5 on 2022-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_topology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydevicesnmpinterface',
            name='adminstatus',
            field=models.CharField(default='down', max_length=50),
        ),
        migrations.AlterField(
            model_name='mydevicesnmpinterface',
            name='inErr',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mydevicesnmpinterface',
            name='inOctect',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mydevicesnmpinterface',
            name='mtu',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mydevicesnmpinterface',
            name='operstatus',
            field=models.CharField(default='down', max_length=50),
        ),
        migrations.AlterField(
            model_name='mydevicesnmpinterface',
            name='outErr',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mydevicesnmpinterface',
            name='outOctect',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mydevicesnmpinterface',
            name='speed',
            field=models.BigIntegerField(default=0),
        ),
    ]
