# Generated by Django 3.2.5 on 2022-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220818_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelinks',
            name='repeat',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
