# Generated by Django 3.2.5 on 2022-10-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_websitelinks_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecapibility',
            name='dbname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicecapibility',
            name='dbport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicecapibility',
            name='dbpwd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicecapibility',
            name='dbuser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
