# Generated by Django 3.2.5 on 2022-10-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_devicecapibility_dbport'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecapibility',
            name='snmpv3auth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicecapibility',
            name='snmpv3pass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicecapibility',
            name='snmpv3user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
