# Generated by Django 3.2.5 on 2022-10-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20221027_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydevicesnmpdata',
            name='cpu',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='mydevicesnmpdata',
            name='uptime',
            field=models.BigIntegerField(default=0),
        ),
    ]
