# Generated by Django 3.2.5 on 2023-03-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20221027_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesetting',
            name='footer',
            field=models.CharField(default="Made with <img src='/static/dashboard/images/heart.png'> in <img src='/static/dashboard/images/india.png'>", max_length=200),
        ),
        migrations.AlterField(
            model_name='notif',
            name='severity',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('predictive', 'Predictive'), ('future', 'Future')], default='low', max_length=50),
        ),
    ]
